<?php

return [
  'permissions'  => [
      'Exporter des données',
      'Créer produit',
      'Modifier produit',
      'Supprimer produit',
      'Créer catégorie',
      'Modifier catégorie',
      'Supprimer catégorie',
      'Créer Fournisseur',
      'Modifier Fournisseur',
      'Supprimer Fournisseur',
      'Créer stock',
      'Modifier stock',
      'Gestion commerce',
      'Créer statut stock',
      'Modifier statut stock',
      'Supprimer statut stock',
      'Créer Utilisateur',
      'Modifier Utilisateur',
      'Supprimer Utilisateur',
      'Gérer les rôles',
      'Gérer les permissions',
      'Créer zone de stockage',
      'Modifier zone de stockage',
      'Supprimer zone de stockage',
  ],
    'gerant' => [
        'Exporter des données',
        'Créer produit',
        'Modifier produit',
        'Supprimer produit',
        'Créer catégorie',
        'Modifier catégorie',
        'Supprimer catégorie',
        'Créer Fournisseur',
        'Modifier Fournisseur',
        'Supprimer Fournisseur',
        'Gestion commerce',
        'Créer stock',
        'Créer statut stock',
        'Modifier statut stock',
        'Supprimer statut stock',
        'Créer Utilisateur',
        'Modifier Utilisateur',
        'Supprimer Utilisateur',
        'Gérer les rôles',
        'Gérer les permissions',
        'Créer zone de stockage',
        'Modifier zone de stockage',
        'Supprimer zone de stockage',
    ],
    'manager' => [
        'Exporter des données',
        'Créer produit',
        'Modifier produit',
        'Supprimer produit',
        'Créer catégorie',
        'Modifier catégorie',
        'Supprimer catégorie',
        'Créer Fournisseur',
        'Modifier Fournisseur',
        'Supprimer Fournisseur',
        'Créer stock',
        'Créer statut stock',
        'Modifier statut stock',
        'Supprimer statut stock',
        'Créer Utilisateur',
        'Modifier Utilisateur',
        'Supprimer Utilisateur',
        'Gérer les rôles',
        'Gérer les permissions',
        'Créer zone de stockage',
        'Modifier zone de stockage',
        'Supprimer zone de stockage',
    ],
    'serveur' => [
        'Créer stock',
        'Modifier statut stock',
    ],
];
